# SPDX-License-Identifier: MIT
# Author:  Giovanni Santini
# Mail:    giovanni.santini@proton.me
# License: MIT

obj-m      += hello.o 
PWD        := $(CURDIR) 
KVERSION   ?= $(shell uname -r)
KERNEL_DIR ?= linux

ARCH_KERNEL = x86
ARCH_QEMU   = x86_64
KERNEL_IMG  = $(KERNEL_DIR)/arch/$(ARCH_KERNEL)/boot/bzImage 
IMG         = qemu-image.img   # use create-image.sh to generate an image
IMG_SIZE    = 1g
IMG_MOUNT   = mount-point.dir
IMG_USER    = root
IMG_PASSWD  = root
PACKAGES    = vim
FS_TYPE     = ext4
ARCH_DEBOOTSTRAP = amd64
QEMU_FLAGS  = -kernel $(KERNEL_IMG) \
	      -hda $(IMG) \
	      -append "root=/dev/sda console=ttyS0" \
	      --enable-kvm

